### ISSUE TITLE
Multiple Release Archives

### ISSUE THREAD

**Issue by x87** [cleolibrary/CLEO5#11]
- base archive w/out ASI loader
- archive with Silent's ASI Loader 1.3
- archive with Ultimate ASI Loader
- archive with SDK (cleo.h and CLEO.lib + docs)

**Comment by MiranDMC** [comment]
SDK for sure should be separated pack, including additionally example plug-in project.

Why multiple ASI loaders even exists? Sillent's one was not good enough?

I think pack for regular user should contain everything that is needed to run it on clean install of GTA.
Perhaps we should add game version info to the main screen, as people never are able to tell when asked during problem solving.

**Comment by CanerKaraca23** [comment]
Why including ASI Loaders to CLEO? I think you should just add a red, bold and big text to GitHub readme and cleo.li website "You need to install Silent's ASI Loader or Ultimate ASI Loader to use CLEO"

But if you want to make a package for regular users, then you should add CLEO+ and NewOpcodes.cleo plugins too because some mods requires it.

**Comment by MiranDMC** [comment]
Yes I also think CLEO+ should be included as default component of CLEO. As I understand it is considered mature and stable project. Recently Orion documented it opcodes on SBL webpage, the opcodes are included in Sanny Builder's opcode search, so why not?

In regards of NewOpcodes: this is closed source, right? I do not think we should ship something we can not fix if problems reported.

**Comment by CanerKaraca23** [comment]
Yes, CLEO+ is really stable and good plugin. As developer said, it's 6x time bigger than CLEO. But unfortunately, developer said he will not update the plugin anymore because he left the community.

https://www.mixmods.com.br/2023/10/cleoplus/

You can ask permission to continue development of CLEO+ and it's already open source. It will be also great  to integrating CLEO+ to CLEO 5.

For NewOpcodes.cleo, it's very old and yes it's not open source, developer left the community years ago. I don't know you can contact him for integrating or continue development. CLEO+ already have some of opcodes from NewOpcodes.cleo but not all of them. Some mods still requires it (for example Emergency Lights Mod and Active Dashboard, they are very popular mods).

**Comment by MiranDMC** [comment]
CLEO+ is ~170 kb after packing, while current CLEO download pack is +700kb, so I do not think this is that much nowadays.

**Comment by MiranDMC** [comment]
Ok I see there is some confusion how CLEO should be installed with UAL. Which files should go to game root, which to the scripts directory. I'm confused myself now, so the UAL pack might be good idea as apparently people are using it.

**Comment by ThirteenAG** [comment]
Isn't cleo path relative to asi? I always put both asi and CLEO folder to scripts, at least in iii or vc.

**Comment by MiranDMC** [comment]
> Isn't cleo path relative to asi? I always put both asi and CLEO folder to scripts, at least in iii or vc.

It is, but how it works with any script expecting to load additional files from cleo folder? These will just try use [game]\cleo path.

**Comment by 1234G-G4321** [comment]
I think, its simple as that..

Packing CLEO.zip with UAL: Content should be.
```
All are in the ROOT folder
- CLEO.asi (Main ASI)
- CLEO (Folder)
- bass.dll
- vorbisFile.dll (UAL)
```

**But not restrict CLEO in Root for the people like ME & ThirteenAG (which want to use with scripts directory)**
 
Note: CLEO scripts not loaded from **scripts\cleo\ [.....cs]**, but at the times its **loads from MODLOADER**

**Conclusion:** Pack CLEO with ROOT, but Not RESTRICT for ROOT.... **Continue with OLDER Behavior..** Its Very Simple

**Comment by 1234G-G4321** [comment]
I think, its simple as that..

Packing CLEO.zip with UAL: Content should be.
```
All are in the ROOT folder
- CLEO.asi (Main ASI)
- CLEO (Folder)
- bass.dll
- vorbisFile.dll (UAL)
```

**But not restrict CLEO in Root for the people like ME & ThirteenAG (which want to use with scripts directory)**
 
Note: CLEO scripts not loaded from **scripts\cleo\ [.....cs]**, but at the times its **loads from MODLOADER**

**Conclusion:** Pack CLEO with ROOT, but Not RESTRICT for ROOT.... **Continue with OLDER Behavior..** Its Very Simple

.
.
.
.
If Include UAL INI, (global.ini)
```
Change
LoadFromScriptsOnly=1
to
LoadFromScriptsOnly=0
```

**Comment by 1234G-G4321** [comment]
I think, its simple as that..

Packing CLEO.zip with UAL: Content should be.
```
All are in the ROOT folder
- CLEO.asi (Main ASI)
- CLEO (Folder)
- bass.dll
- vorbisFile.dll (UAL)
```

**But not restrict CLEO in Root for the people like ME & ThirteenAG (which want to use with scripts directory)**
 
Note: CLEO scripts not loaded from **scripts\cleo\ [.....cs]**, but at the times its **loads from MODLOADER**

**Conclusion:** Pack CLEO with ROOT, but Not RESTRICT for ROOT.... **Continue with OLDER Behavior..** Its Very Simple

.
.
.
.
If Include UAL INI, (scripts\global.ini)
```
Change
LoadFromScriptsOnly=1
to
LoadFromScriptsOnly=0
```
