### ISSUE TITLE
Mod not working again...

### ISSUE THREAD

**Issue by CanerKaraca23** [cleolibrary/CLEO5#180]
https://github.com/cleolibrary/CLEO5/issues/26

![ss](https://github.com/user-attachments/assets/40cf9082-9f9e-455c-bc3b-cb856632a8c0)

**Comment by x87** [comment]
@CanerKaraca23 is this still an issue with latest build? Can you share the script?

**Comment by CanerKaraca23** [comment]
> @CanerKaraca23 is this still an issue with latest build? Can you share the script?

Yes, i still have.

https://www.mixmods.com.br/2018/01/elm-emergency-lights-mod-v1-0-by-nyolc8/

**Comment by MiranDMC** [comment]
@CanerKaraca23 Any extra reproduction details? I just tried it with alpha.70 and it seems to work ok.
I extracted mod to main cleo directory and changed two main scripts filetype to .cs4

**Comment by MiranDMC** [comment]
Offset {118} from screen does not make much sense in that script:
```
{0} write_debug "SAMP CHAT STATE HELPER 1.0"
{30} write_debug "BY NYOLC8"
{43} write_debug "MADE FOR CONVOY TRUCKING COMMUNITY"
{81} write_debug "WWW.CONVOYTRUCKING.NET"
{107} script_name "SAMP_CHAT_STATE_HELPER"
{133} wait 1000
```
Are you sure that file is not damaged? Do you have CLEO Redux installed?

**Comment by CanerKaraca23** [comment]
@MiranDMC I don't have CLEO Redux, i just open my game and it gives this error on launch. Files are not damaged, just downloaded again and renamed to .cs4 and still same. It's in cleo folder, not modloader.

**Comment by MiranDMC** [comment]
Ok I'm now experiencing similar problem, but with my simple script, so there is something weird actually.

**Comment by MiranDMC** [comment]
@CanerKaraca23 Ok the error I had was caused by starting mission script while another mission was in progress. Your issue is totally different.
Due to inability to reproduce at our side please do troubleshooting:
Make directory with clear GTA SA inside, put CLEO5 in it and Emergency light mod. Should work. Then try copying mods you have from your current game one by one and checking if it still works.
Seems like some cross contamination.

**Comment by CanerKaraca23** [comment]
> @CanerKaraca23 Ok the error I had was caused by starting mission script while another mission was in progress. Your issue is totally different. Due to inability to reproduce at our side please do troubleshooting: Make directory with clear GTA SA inside, put CLEO5 in it and Emergency light mod. Should work. Then try copying mods you have from your current game one by one and checking if it still works. Seems like some cross contamination.

I think i found the issue. The issue is OpenMP Launcher, and it's really odd. Because i don't have issue with SAMP's own launcher. Sorry for wasting your time. I was tried on vanilla (no mods) game on SAMP but with OpenMP Launcher and then somehow I guessed maybe it's because of OpenMP and yes...

You can close the issue, i will open issue on OpenMP Launcher. @MiranDMC

**Comment by x87** [comment]
@CanerKaraca23 can you confirm if this script works or not with CLEO 4.4.4 and OpenMP?

**Comment by CanerKaraca23** [comment]
> @CanerKaraca23 can you confirm if this script works or not with CLEO 4.4.4 and OpenMP?

@x87 I didn't tested with 4.4.4 but, yes it gives error with OpenMP but mod works. Without OpenMP, it's fine.

I can test with OpenMP + 4.4.4 if you want.

**Comment by MiranDMC** [comment]
So issue was caused by OpenMP installing its own (faulty) hook on get tring script param function.
CLEO4 did not reported invalid/unknown opcodes, it just skipped 2 bytes and tried to read next data as opcodes.
In that script faulty read param function was leaving 4 unprocessed bytes, which then were ignored and by luck next command was processed correctly. 
It would not work if script name length was even.
